#[path = "../../../src/config.rs"]
pub mod config;
#[path = "../../../src/connections.rs"]
pub mod connections;
#[path = "../../../src/core/mod.rs"]
pub mod core;
#[path = "../../../src/default_apps.rs"]
pub mod default_apps;
#[path = "../../../src/diag.rs"]
pub mod diag;
#[path = "../../../src/launcher.rs"]
pub mod launcher;
#[path = "../../../src/pty.rs"]
pub mod pty;
#[path = "../../../src/session.rs"]
pub mod session;
#[path = "../../../src/sound.rs"]
pub mod sound;
#[path = "../../../src/status.rs"]
pub mod status;
#[path = "../../../src/ui.rs"]
pub mod ui;
